### ISSUE TITLE
Add option to create waveform files for GHDL (GUI mode)

### ISSUE THREAD

**Issue by Paebbels** [OSVVM/OSVVM-Scripts#11]
Please add an option to GHDL, so waveform files in GHW format can be created. These can then be viewed and analyzed with GTKwave.

The needed option is `--wave=${LibraryUnit}.ghw ` after the `LibraryUnit`.

Here a diff from my workaround:
```diff
- exec echo "$ghdl --elab-run --std=${VhdlShortVersion} --syn-binding --work=${LibraryName} --workdir=${GHDL_WORKING_LIBRARY_PATH} ${VHDL_RESOURCE_LIBRARY_PATHS} ${LibraryUnit}" | {*}[get_tee]
+ exec echo "$ghdl --elab-run --std=${VhdlShortVersion} --syn-binding --work=${LibraryName} --workdir=${GHDL_WORKING_LIBRARY_PATH} ${VHDL_RESOURCE_LIBRARY_PATHS} ${LibraryUnit}" --wave=${LibraryUnit}.ghw | {*}[get_tee]
```

Ideally, OSVVM scripting could offer a GUI mode / switch / variable.
* in case of a `vlib/vcom/vsim` interface compatible simulator: launch simulator in GUI mode.
* in case of GHDL: write a waveform file in GHW format.

**Comment by Paebbels** [comment]
Please note, `--wave` is a runtime option, so it must be specified <u>after</u> the `${LibraryUnit}`.

![image](https://user-images.githubusercontent.com/956109/154788715-e0ed9579-6132-4308-b950-cacf122d6d50.png)  
See https://ghdl.github.io/ghdl/using/InvokingGHDL.html#elaborate-and-run-elab-run

**Comment by Paebbels** [comment]
I think this is now covered by `SetExtendedSimulateOptions`.

How to set a single and how to set multiple options?
The documentation mentions only a single value.

Examples:
* `--wave=Testbench.ghw`
* `--wave=Testbench.ghw --stop-time=100us`

**Comment by JimLewis** [comment]
SetExtendedElaborateOptions, SetExtendedRunOptions, and SetSaveWaves were on main branch.   Still have to add documentation for them.

**Comment by Paebbels** [comment]
It doesn't appear in the documentation at https://github.com/PLC2/OSVVM-Scripts/blob/main/README.rst, right?
