### ISSUE TITLE
Allow referencing pre-compiled vendor libraries for Active-HDL/Riviera-PRO

### ISSUE THREAD

**Issue by Paebbels** [OSVVM/OSVVM-Scripts#12]
In case of OSVVM-based simulation containing encrypted IP cores from e.g. Xilinx Vivado, OSVVM should offer a generic solution to reference pre-compiled vendor libraries.

In our current approach, we use the `vmap` command in OSVVM's `*.pro` files to reference a directory containing pre-compiled IP cores. The referenced directory (e.g. `dds_compiler_v6_0_20`) is referenced and then added by Riviera-PRO to the local `library.cfg` file.

While this solution solves the problem, a more generic OSVVM-like TCL procedure should be offered to reference pre-compile libraries or IP cores.

**Example:**
```tcl
vmap dds_compiler_v6_0_20 {C:/Tools/Precompiled/Riviera-PRO/2021.10/Vivado/2020.2/dds_compiler_v6_0_20}
vmap xbip_utils_v3_0_10 {C:/Tools/Precompiled/Riviera-PRO/2021.10/Vivado/2020.2/xbip_utils_v3_0_10}
vmap xbip_pipe_v3_0_6 {C:/Tools/Precompiled/Riviera-PRO/2021.10/Vivado/2020.2/xbip_pipe_v3_0_6}
vmap axi_utils_v2_0_6 {C:/Tools/Precompiled/Riviera-PRO/2021.10/Vivado/2020.2/axi_utils_v2_0_6}
vmap unisim {C:/Tools/Precompiled/Riviera-PRO/2021.10/Vivado/2020.2/unisim}
vmap xbip_dsp48_multadd_v3_0_6 {C:/Tools/Precompiled/Riviera-PRO/2021.10/Vivado/2020.2/xbip_dsp48_multadd_v3_0_6}
vmap xbip_bram18k_v3_0_6 {C:/Tools/Precompiled/Riviera-PRO/2021.10/Vivado/2020.2/xbip_bram18k_v3_0_6}

library myProject
include ../../src/common.pro
include ../../src/testbench.pro
```

**Comment by Paebbels** [comment]
How to call this TCL command?
Does you have an example or can you post one of the above lines how it would look like?

**Comment by JimLewis** [comment]
LinkLibrary <logical library name> <LibraryDirectory>

WRT <Library directory> it is going to go through a search for OSVVM type patterns, but if it does not find any, then it uses that path as the actual directory of the library.   

OSVVM Library search looks for the existence of the following paths: 
<LibraryDirectory>/VHDL_LIBS/<tool_revision>/<lower case logical library name>
<LibraryDirectory>/VHDL_LIBS/<tool_revision>
<LibraryDirectory>/<tool_revision>/<lower case logical library name>
<LibraryDirectory>/<tool_revision>
<LibraryDirectory>/<lower case logical library name>
<LibraryDirectory>

When you are using an externally generated library, you are following the last case <LibraryDirectory>.

OSVVM creates library names in the following format:
<LibraryDirectory>/VHDL_LIBS/<tool_revision>/<lower case logical library name>

LinkLibrary allows the above to be specified as any of the following.  The idea is if they are confused as to which to specify for the library path, it just works with anything sensible.
<LibraryDirectory>
<LibraryDirectory>/VHDL_LIBS
<LibraryDirectory>/VHDL_LIBS/<tool_revision>
<LibraryDirectory>/VHDL_LIBS/<tool_revision>/<lower case logical library name>

**Comment by JimLewis** [comment]
Sometimes I really hate md.  Like when I need to specify \< and \>

**Comment by Paebbels** [comment]
use `&gt;` and `%lt;` for \< and \>

These examples look like the external library must be in the OSVVM directory. That's not the case with pre-compile vendor libraries as these are pre-compiled one per machine in a central directly or network share.

**Comment by JimLewis** [comment]
All except for the last form which takes any old directory you wish.

**Comment by JimLewis** [comment]
Since your library name and the directory name match, you can also do:
`LinkLibraryDirectory C:/Tools/Precompiled/Riviera-PRO/2021.10/Vivado/2020.2`

And that will get all of them.

**Comment by JimLewis** [comment]
BTW, since your directory names match the library name, both LinkLibrary and LinkLibraryDirectory should work with the 2022.01 release and it does not need the fix I just did.   The fix I just did addresses situations like where the logical library name is fred and it is in directory fred_1.41.
That would need the newer code that is in Dev.

**Comment by JimLewis** [comment]
@Paebbels   Please review the above about LinkLibraryDirectory. 

Please close this issue if you think that addressed it.   If not, please explain how it does not.
