### ISSUE TITLE
Missing indentation in YAML created by OSVVM

### ISSUE THREAD

**Issue by Paebbels** [OSVVM/OSVVM-Scripts#14]
The generated YAML output of OSVVM has a missing indentation level before echt testcase.

![image](https://user-images.githubusercontent.com/956109/150684735-a970e60f-633a-4e0d-92d6-3e3a7bbea1ed.png)

**Corrected Output as diff:**
```diff
TestSuites: 
  - Name: Axi4Lite
    TestCases:
-    - TestCaseName: TbAxi4_BasicReadWrite
-      Name: "TbAxi4_BasicReadWrite"
-      Status: PASSED
+      - TestCaseName: TbAxi4_BasicReadWrite
+        Name: "TbAxi4_BasicReadWrite"
+        Status: PASSED
```

-------------
I haven't checks on functional coverage YAML files.

**Comment by Paebbels** [comment]
Was this fixed in the last release?

**Comment by JimLewis** [comment]
Is this pedantic or Is it breaking something?   TCL YAML reader is reading it just fine.  If it is breaking the EDAA reader, I will prioritize it higher.

**Comment by Paebbels** [comment]
Some reader do read it, but the syntax is not correct.

So priority is low, but should be fixed.

**Comment by JimLewis** [comment]
Agreed.  It is on my list, but lower than the large list of other things that must be done.   But it will get done as sometimes it just feels good to get things off the list.

**Comment by JimLewis** [comment]
Fixed in next release
