### ISSUE TITLE
How to use OSVVM Predefined Variables in TCL?

### ISSUE THREAD

**Issue by Paebbels** [OSVVM/OSVVM-Scripts#20]
OSVVM-Scripts offers some internal variables for explicit usage by the user like `$::osvvm::ToolVendor`.

The documentation misses:
* a list of available variables
* a list of allowed values

**Example:**  
`$::osvvm::ToolVendor` gives the vendor name of the active simulation tool. From OSVVM examples like OSVVM Utility Library, we can find values like `Aldec`.

But it's unclear how to write GHDL for a string compare. Is it `GHDL`, `ghdl`, ...  
Is GHDL even a vendor?

Please document these variables and possible values and a comparison example.

**Comment by JimLewis** [comment]
Documentation of the variables is a work in progress.   Would you prefer this in the Scripts_user_guide / README.rst or would you like it in a code file - such as the OsvvmDefaultSettings.tcl (new in Dev).   

Do you have a suggestion GHDL?

**Comment by JimLewis** [comment]
I am keeping this as a placeholder for 2022.09 documenation of new scripting features.
Variables noted above
https://github.com/OSVVM/OSVVM-Scripts/issues/21
https://github.com/OSVVM/OSVVM-Scripts/issues/17
https://github.com/OSVVM/OSVVM-Scripts/issues/19
https://github.com/OSVVM/OSVVM-Scripts/issues/11

**Comment by JimLewis** [comment]
Variables that are different for each simulator are shown in the README.rst / Script_userguide.pdf.   For details on other settings see Example_LocalScriptDefaults.tcl.   This file is a template.   Copy it to LocalScriptDefaults.tcl and edit to modify your settings.
