### ISSUE TITLE
Return a non-zero exit code, when testsuite has failing tests

### ISSUE THREAD

**Issue by Paebbels** [OSVVM/OSVVM-Scripts#21]
Currently, a testsuite with failing tests returns an exit code of `0`.

Proposed exit codes:
* `0` - all OK: analysis, simulation, report generation (TCL after scripts)
* `1` - analysis failed with compilation errors from vcom, vlog, ...  
  (see #15)
* `2` - at least one simulation failed with errors
* `3` - all simulations are OK, but there have been errors in after scripts (e.g. report generations)

Maybe an option is required to configure if an overall run should fail if after-scripts had errors.  
`SetIgnoreErrorsInReporting true`

**Comment by Paebbels** [comment]
I think you address this issue, right?

**Comment by JimLewis** [comment]
Done.    Documentation coming in 2022.09.
