### ISSUE TITLE
Riviera-PRO scripting broken on Linux due to typos

### ISSUE THREAD

**Issue by Asif71** [OSVVM/OSVVM-Scripts#28]
Riviera-PRO can't be executed in CI (Linux environment) due to different spellings of Riviera-PRO vs. Riviera-Pro vs. maybe others. This behavior can't be seen on Windows because it's case insensitive.

Spelling differences according to TCL error messages from CI:
1. > SCRIPTER: Error: couldn't read file "/builds/...../lib/OSVVM-Scripts/VendorScripts_RivieraPRO.tcl": no such file or directory  
   
   Identified script line: https://github.com/OSVVM/OSVVM-Scripts/blob/main/StartUp.tcl#L78  
   ```tcl
   variable ScriptBaseName   "RivieraPRO"
   ```
   vs.
   `VendorScripts_RivieraPro.tcl`

Please also check in other places and for other simulator tools.  
TCL is only reporting the first error and aborts execution.

-----
/cc @Paebbels, @plc2

**Comment by JimLewis** [comment]
Thanks.   A fix was pushed onto Dev branch.

**Comment by Asif71** [comment]
Hello Jim, I checked out your latest dev branch commit ID fba9cd6e. Unfortunately I still have same error message. I cross checked the case of word "Pro" but you did not change anything for that.

```
SCRIPTER: Error: couldn't read file "/builds/...../lib/OSVVM-Scripts/VendorScripts_RivieraPRO.tcl": no such file or directory
```

**Comment by JimLewis** [comment]
Looks like I forgot to push the scripts submodule.   I have done that now.
