### ISSUE TITLE
Disable execution of wave.do in non-gui mode

### ISSUE THREAD

**Issue by riedel-ferringer** [OSVVM/OSVVM-Scripts#29]
I can only speak for ModelSim, but there you don't want to source 'wave.do' if no GUI is open. This would result in tons of error messages, because "signals cannot be added to a (non-existent) waveform view", etc etc

Suggested solution in OsvvmProjectScripts.tcl

```
proc SimulateRunSubScripts {LibraryUnit Directory} {
  variable ToolVendor
  variable ToolName
  variable NoGui
  
  RunIfExists [file join ${Directory} ${ToolVendor}.tcl]
  RunIfExists [file join ${Directory} ${ToolName}.tcl]
  if {! $NoGui} {
    RunIfExists [file join ${Directory} wave.do]
  }
  SimulateRunDesignScripts ${LibraryUnit} ${Directory}
}
```

**Comment by JimLewis** [comment]
Thanks.   

This makes an interesting point in that what do we put in the files ${TestName}.tcl?   Do we expect the author of these files to mask out waveforms as above?

**Comment by riedel-ferringer** [comment]
In that case, I would say it's up to the author of the respective file. Because creating it must be done explicitly. Loading a wave.do, on the other hand, is done implicilty. 'wave.do' is the default name, so it might be there "accidentially" and should thus not break the simulation.

**Comment by f-markus** [comment]
Now part of PR 35 (https://github.com/OSVVM/OSVVM-Scripts/pull/35)

**Comment by JimLewis** [comment]
This was already done to the dev branch.
