### ISSUE TITLE
Don't stop simulation in case wave.do produces errors

### ISSUE THREAD

**Issue by f-markus** [OSVVM/OSVVM-Scripts#33]
The wave.do is usually a GUI-only script, which defines the signals to be displayed in the waveform viewer. I think it would be better to ignore errors that are thrown by this script, because they usually are not of interest. Usually, it just reports that one or another signalname could not be found in the design. IMHO, that's no reason to stop simulating.

```
if {[catch {RunIfExists [file join ${Directory} wave.do]} errorMsg]} {
  puts "Error loading wave.do: $errorMsg"
}
```

**Comment by JimLewis** [comment]
Fixed in Dev
