### ISSUE TITLE
OSVVM-Scripts doesn't Detect Simulator Tool Correctly if not Installed in Default Directory

### ISSUE THREAD

**Issue by Paebbels** [OSVVM/OSVVM-Scripts#4]
# Problem Description

I installed my Riviera-PRO installation into `C:\Aldec\Riviera-PRO\2020.04`. This leads to a different value in environment variable `ALDEC`, which contains the installation path. I use a subdirectory to handle multiple parallel Aldec tool installations.

```
C:\
  Aldec\
    Riviera-PRO\
      2019.10\
      2020.04\
```

# Current Behavior

`ToolConfiguration.tcl` doesn't detect the tool correctly if e.g. installation directory is not the default tool directory.
As fallback, Active-HDL is assumed.

# Expected Behavior

Detect `Riviera-PRO`. Emit an error if tool isn't detected, don't assume Active-HDL as fallback.

# Workaround

Change line 74 to:
```tcl
if {[string match [string index $ToolExecutableName 0] "r"]} {
```

![image](https://user-images.githubusercontent.com/956109/94108649-f5e45c80-fe3f-11ea-9e88-a70f618e6b24.png)

**Comment by JimLewis** [comment]
This should be fixed in the current release
