### ISSUE TITLE
Bug wrt. variable-existence checks

### ISSUE THREAD

**Issue by riedel-ferringer** [OSVVM/OSVVM-Scripts#50]
https://github.com/OSVVM/OSVVM-Scripts/blob/778e6b9e1931dcddb3249da7759296026f9be099/OsvvmProjectScripts.tcl#L217C24-L217C24

I had to change the check to 
`if {[info exists ::argv0]} {`
as otherwise I got an error "$::argv0 not found" in the next line...

**Comment by JimLewis** [comment]
Should be fixed in the current release
